#
# Cluster admin
#

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-admin
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["*"]

# 
# Cluster viewer
#

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-viewer
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]

#
# Secret manage
# * according to table and task it's supposed to be read only
#

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  namespace: prop-development
  name: cluster-secret-manager
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch"]
